/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DateRouteRouteImport } from './routes/$date/route'

const DateRouteRoute = DateRouteRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$date': typeof DateRouteRoute
}
export interface FileRoutesByTo {
  '/$date': typeof DateRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$date': typeof DateRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$date'
  fileRoutesByTo: FileRoutesByTo
  to: '/$date'
  id: '__root__' | '/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DateRouteRoute: typeof DateRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$date': {
      id: '/$date'
      path: '/$date'
      fullPath: '/$date'
      preLoaderRoute: typeof DateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DateRouteRoute: DateRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
